[package]
name = "plugin_sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "plugin_sdk_rust"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1" }
